// src/components/Cell/Cell.tsx
import { useMemo } from "react";

type CellProps = {
    index: number,
    styles: any
}

export default function Cell({ index, styles }: CellProps) {
    const color = useMemo(() => (index % 8 + Math.floor(index / 8)) % 2, [index]);
    const [x, y] = useMemo(() => [String.fromCharCode(65 + 7 - index % 8), Math.floor(index / 8) + 1], [index]);

    return (
        <div data-x={x} data-y={y} className={`${styles.cell} ${styles[color ? 'black' : 'white']} ${y === 1 ? styles.labelBottom : ''} ${x === 'A' ? styles.labelLeft : ''}`}></div>
    );
}

// src/components/Cell.svelte
<script lang="ts">
    export let index: number;
    const color = (index % 8 + Math.floor(index / 8)) % 2;
    const [x, y] = [String.fromCharCode(65 + 7 - index % 8), Math.floor(index / 8) + 1];
</script>

<style lang="scss">
    .cell {
        width: 50px;
        height: 50px;
        aspect-ratio: 1;
    }
</style>

<div class="cell" style={`background: ${color ? 'black': 'white'}; color: ${!color ? 'black': 'white'}`}>
    { x } { y } {color ? 'black': 'white'}
</div>
